start_param: [-40.752, -15.801]

goal_x_params: [
                    -24.450,
                    -24.539,
                    -24.905,
                    -40.922,
                    -58.334,
                    -58.370,
                    -58.037,
                    -40.752
                ]

goal_y_params: [
                    -15.122,
                    -8.177,
                    -1.161,
                    -2.004,
                    -2.522,
                    -9.291,
                    -16.044,
                    -15.801
                ]