start_param: [-1.713, 0.143]

goal_x_params: [
                    12.975,
                    13.232,
                    13.635,
                    -2.018,
                    -18.403,
                    -20.150,
                    -20.585,
                    -1.319
               ]

goal_y_params: [
                    -0.311,
                    6.559,
                    13.576,
                    13.643,
                    14.681,
                    7.718,
                    0.471,
                    -0.006
                ]
